# Generated by Django 3.1.7 on 2021-03-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('FN', 'Full Name'), ('J', 'Job'), ('E', 'Email'), ('DN', 'Domain Name'), ('PN', 'Phone Number'), ('T', 'Text'), ('I', 'Integer'), ('A', 'Address'), ('D', 'Data')], max_length=2)),
                ('range', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_generator.schema')),
            ],
            options={
                'verbose_name': 'Column',
                'verbose_name_plural': 'Columns',
                'db_table': 'columns',
            },
        ),
    ]
