# Generated by Django 3.1.7 on 2021-03-18 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0002_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_generator.schema')),
            ],
            options={
                'verbose_name': 'Fake Data',
                'verbose_name_plural': 'Fake Datas',
                'db_table': 'fake_datas',
            },
        ),
    ]
