# Generated by Django 3.1.7 on 2021-03-25 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0004_auto_20210325_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='order',
        ),
    ]
